// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"fmt"
	"gokick/app"
	"gokick/app/application/auth/command"
	"gokick/app/application/bus"
	"gokick/app/application/bus/middleware"
	query3 "gokick/app/application/dashboard/query"
	job2 "gokick/app/application/job"
	command2 "gokick/app/application/profile/command"
	"gokick/app/application/profile/query"
	command3 "gokick/app/application/user/command"
	query2 "gokick/app/application/user/query"
	job3 "gokick/app/domain/job"
	"gokick/app/domain/shared"
	token2 "gokick/app/domain/token"
	"gokick/app/infrastructure/config"
	"gokick/app/infrastructure/database"
	"gokick/app/infrastructure/scheduler"
	"gokick/app/infrastructure/security"
	"gokick/app/infrastructure/sqlite/audit"
	"gokick/app/infrastructure/sqlite/job"
	"gokick/app/infrastructure/sqlite/seeder"
	"gokick/app/infrastructure/sqlite/token"
	"gokick/app/infrastructure/sqlite/user"
	"gokick/app/infrastructure/worker"
	"gokick/app/presentation/console"
	"gokick/app/presentation/http/handler"
	middleware2 "gokick/app/presentation/http/middleware"
	"gokick/app/presentation/http/server"
	"gokick/public"
	"io/fs"
	"log/slog"
	"time"
)

// Injectors from container_provider.go:

func CreateApplication(logger *slog.Logger, reporter shared.ErrorReporter) (*app.Application, error) {
	configConfig, err := config.LoadConfig()
	if err != nil {
		return nil, err
	}
	jwtService, err := security.NewJwtService(configConfig)
	if err != nil {
		return nil, err
	}
	ipExtractor := provideIPExtractor(configConfig)
	rateLimiters, err := provideRateLimiters(configConfig, ipExtractor, logger)
	if err != nil {
		return nil, err
	}
	healthHandler := handler.NewHealthHandler()
	fs := providePublicFS()
	spaConfig := provideSPAConfig(configConfig)
	spaHandler := handler.NewSPAHandler(logger, fs, spaConfig)
	cookieSecure := provideCookieSecure(configConfig)
	sqliteManager, err := database.NewSqliteManager(configConfig)
	if err != nil {
		return nil, err
	}
	permissionChecker := providePermissionChecker()
	v := provideEventHandlers()
	eventBus := provideEventBus(logger, v, reporter)
	repository := job.NewRepository(sqliteManager)
	handlerRegistry, err := provideJobHandlerRegistry()
	if err != nil {
		return nil, err
	}
	jobDispatcher := provideJobDispatcher(repository, handlerRegistry)
	auditRepository := audit.NewRepository(sqliteManager)
	commandBus := provideCommandBus(logger, sqliteManager, permissionChecker, eventBus, jobDispatcher, auditRepository, reporter)
	userRepository := user.NewRepository(sqliteManager)
	tokenRepository := token.NewRepository(sqliteManager)
	passwordHasher := providePasswordHasher()
	loginHandler := command.NewLoginHandler(userRepository, tokenRepository, passwordHasher, jwtService)
	refreshTokenHandler := command.NewRefreshTokenHandler(userRepository, tokenRepository, jwtService)
	logoutHandler := command.NewLogoutHandler(tokenRepository)
	permissionsRegistry := providePermissionsRegistry()
	authHandler := handler.NewAuthHandler(cookieSecure, commandBus, loginHandler, refreshTokenHandler, logoutHandler, permissionsRegistry)
	queryBus := provideQueryBus(logger, permissionChecker, reporter)
	getProfileHandler := query.NewGetProfileHandler(userRepository)
	changePasswordHandler := command2.NewChangePasswordHandler(userRepository, passwordHasher)
	profileHandler := handler.NewProfileHandler(commandBus, queryBus, getProfileHandler, changePasswordHandler, permissionsRegistry)
	listUsersHandler := query2.NewListUsersHandler(userRepository)
	createUserHandler := command3.NewCreateUserHandler(userRepository, passwordHasher)
	updateUserHandler := command3.NewUpdateUserHandler(userRepository, passwordHasher)
	deleteUserHandler := command3.NewDeleteUserHandler(userRepository)
	adminUsersHandler := handler.NewAdminUsersHandler(commandBus, queryBus, listUsersHandler, createUserHandler, updateUserHandler, deleteUserHandler)
	getUserDashboardHandler := query3.NewGetUserDashboardHandler()
	getAdminDashboardHandler := query3.NewGetAdminDashboardHandler()
	dashboardHandler := handler.NewDashboardHandler(queryBus, getUserDashboardHandler, getAdminDashboardHandler)
	serverServer := server.NewServer(configConfig, logger, reporter, jwtService, rateLimiters, ipExtractor, healthHandler, spaHandler, authHandler, profileHandler, adminUsersHandler, dashboardHandler)
	v2 := provideSchedulerJobs(tokenRepository)
	scheduler, err := provideScheduler(logger, v2)
	if err != nil {
		return nil, err
	}
	worker := provideWorker(logger, reporter, repository, handlerRegistry, sqliteManager, jobDispatcher)
	serveCommand := console.NewServeCommand(serverServer, scheduler, worker)
	seedAdminPassword := provideSeedAdminPassword(configConfig)
	seederSeeder := seeder.NewSeeder(userRepository, passwordHasher, seedAdminPassword, logger)
	seedCommand := console.NewSeedCommand(seederSeeder)
	createUserCommand := console.NewCreateUserCommand(createUserHandler)
	workerCommand := console.NewWorkerCommand(worker)
	rootCommand := console.NewRootCommand(serveCommand, seedCommand, createUserCommand, workerCommand)
	migrationManager := database.NewMigrationManager(sqliteManager, logger)
	application := app.NewApplication(rootCommand, migrationManager)
	return application, nil
}

// container_provider.go:

func providePasswordHasher() shared.PasswordHasher {
	return security.NewPasswordHasher()
}

func providePermissionChecker() shared.PermissionChecker {
	return security.NewPermissionChecker()
}

// provideCommandBus wires the write-side bus. Audit wraps OUTSIDE both
// DispatchEvents and Transaction so security-relevant events persist even
// when business work rolls back. JobDispatcher sits outside Transaction so
// the dispatcher is injected before tx begin — Enqueue itself uses Conn(ctx),
// joining the transaction when called from a handler.
func provideCommandBus(
	logger *slog.Logger,
	db *database.SqliteManager,
	checker shared.PermissionChecker,
	eventBus *bus.EventBus,
	dispatcher shared.JobDispatcher, audit2 shared.AuditLogger,

	reporter shared.ErrorReporter,
) *bus.CommandBus {
	chain := append(middleware.BaseChain(logger, checker, reporter), middleware.AuditMiddleware(logger, audit2), middleware.JobDispatcherMiddleware(dispatcher), middleware.DispatchEventsMiddleware(logger, eventBus), middleware.TransactionMiddleware(db))
	return bus.NewCommandBus(chain...)
}

func provideQueryBus(
	logger *slog.Logger,
	checker shared.PermissionChecker,
	reporter shared.ErrorReporter,
) *bus.QueryBus {
	return bus.NewQueryBus(middleware.BaseChain(logger, checker, reporter)...)
}

func providePublicFS() fs.FS {
	return public.FS
}

// provideSPAConfig narrows *config.Config down to the deployment-specific
// frontend values the SPA handler injects into index.html, keeping the handler
// layer free of an infrastructure/config import.
func provideSPAConfig(cfg *config.Config) handler.SPAConfig {
	return handler.SPAConfig{
		SentryDSN:         cfg.FrontendSentryDSN,
		SentryEnvironment: cfg.SentryEnvironment,
		SentryDebug:       cfg.SentryDebug,
	}
}

// provideEventHandlers is the single source of truth for event subscriptions
// — mirrors providePermissionsRegistry / provideSchedulerJobs. Add a new
// entry here; provideEventBus wires them up during construction.
func provideEventHandlers() []bus.EventHandlerEntry {
	return []bus.EventHandlerEntry{}
}

func provideEventBus(
	logger *slog.Logger,
	handlers []bus.EventHandlerEntry,
	reporter shared.ErrorReporter,
) *bus.EventBus {
	eb := bus.NewEventBus(middleware.RecoveryMiddleware(logger, reporter), middleware.LoggingMiddleware(logger))
	for _, h := range handlers {
		eb.Register(h.Event, h.Handler)
	}
	return eb
}

func provideCookieSecure(cfg *config.Config) handler.CookieSecure {
	return handler.CookieSecure(cfg.CookieSecure)
}

// provideIPExtractor is the single source of truth for how a request's
// client IP is resolved — rate limiters and the audit IP middleware both
// pull from it so flipping APP_TRUST_PROXY_HEADERS keeps them in sync.
func provideIPExtractor(cfg *config.Config) middleware2.IPExtractor {
	return middleware2.NewIPExtractor(cfg.TrustProxyHeaders)
}

// provideRateLimiters parses the configured per-IP buckets at startup so a
// malformed APP_RATE_LIMIT_* fails fast instead of silently disabling
// protection.
func provideRateLimiters(
	cfg *config.Config,
	extract middleware2.IPExtractor,
	logger *slog.Logger,
) (*server.RateLimiters, error) {
	loginRule, err := middleware2.ParseRateRule(cfg.RateLimitLogin)
	if err != nil {
		return nil, fmt.Errorf("APP_RATE_LIMIT_LOGIN: %w", err)
	}
	refreshRule, err := middleware2.ParseRateRule(cfg.RateLimitRefresh)
	if err != nil {
		return nil, fmt.Errorf("APP_RATE_LIMIT_REFRESH: %w", err)
	}
	return &server.RateLimiters{
		Login:   middleware2.NewRateLimiter(loginRule, extract, logger),
		Refresh: middleware2.NewRateLimiter(refreshRule, extract, logger),
	}, nil
}

// provideSeedAdminPassword surfaces the seed admin password as a distinct
// Wire-bound type so the seeder's constructor can take it without colliding
// with other strings in the DI graph.
func provideSeedAdminPassword(cfg *config.Config) seeder.SeedAdminPassword {
	return seeder.SeedAdminPassword(cfg.SeedAdminPassword)
}

// provideSchedulerJobs is the single source of truth for periodic in-process
// jobs — mirrors providePermissionsRegistry / provideJobHandlerRegistry. Add
// a new Job here; provideScheduler stays decoupled from job business.
func provideSchedulerJobs(tokens token2.TokenRepository) []scheduler.Job {
	return []scheduler.Job{
		{
			Name:     "cleanup:expired-refresh-tokens",
			Interval: 1 * time.Hour,
			Fn:       tokens.DeleteExpired,
		},
	}
}

func provideScheduler(logger *slog.Logger, jobs []scheduler.Job) (*scheduler.Scheduler, error) {
	return scheduler.NewScheduler(logger, jobs)
}

// provideJobHandlerRegistry collects every kind → handler the binary can
// process. Empty for now — handlers will be added in subsequent phases as
// real background work appears.
func provideJobHandlerRegistry() (*job2.HandlerRegistry, error) {
	return job2.NewHandlerRegistry(map[string]job2.HandlerFunc{})
}

// provideJobDispatcher returns the dispatcher as a domain interface so command
// handlers and event handlers depend on shared.JobDispatcher, not on the
// concrete application-layer type.
func provideJobDispatcher(
	repo job3.Repository,
	registry *job2.HandlerRegistry,
) shared.JobDispatcher {
	return job2.NewDispatcher(repo, registry)
}

// provideWorker wires the persistent job worker. Concurrency stays at 1 by
// default because SQLite serializes writers (WAL: one writer at a time);
// more goroutines don't increase throughput for DB-bound handlers.
func provideWorker(
	logger *slog.Logger,
	reporter shared.ErrorReporter,
	repo job3.Repository,
	registry *job2.HandlerRegistry,
	db *database.SqliteManager,
	dispatcher shared.JobDispatcher,
) *worker.Worker {
	return worker.NewWorker(logger, reporter, repo, registry, db, dispatcher, 1)
}

func providePermissionsRegistry() *shared.PermissionsRegistry {
	return shared.NewPermissionsRegistry([]shared.Permissioned{command.LogoutCommand{}, command2.ChangePasswordCommand{}, query.GetProfileQuery{}, command3.CreateUserCommand{}, command3.UpdateUserCommand{}, command3.DeleteUserCommand{}, query2.ListUsersQuery{}, query3.GetUserDashboardQuery{}, query3.GetAdminDashboardQuery{}})
}
